### ISSUE TITLE
Should exa.editor.Editor.find return OrderedDict values?

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exa#127]
The odict doesn't seem to provide advantages over, for example, a simpler list of tuples that has the same data, i.e.:

```
{'find_key1': OrderedDict([(lineno1, 'value1'), ('lineno2', 'value2']),
 'find_key2': ...}
```
versus
```
{'find_key': [(lineno1, 'value1'), (lineno2, 'value2')], 'find_key2': ...}
```

IMO changing to list of tuples simplifies parsing functions in packages such as exatomic, exadf, etc.

**Comment by tjduigna** [comment]
I wholeheartedly agree; we avoid the cumbersome list(ordereddict).keys())[0] in getting the first line number of a find match, a common occurrence.

I also propose a "control=-1" kwarg to the find function that would behave something like:
if control == -1: behave as normal
if control == 0: return the list of [lineno1, lineno2, lineno3, ....]
if control == 1: return the list of ['value1', 'value2', 'value3', ....]

Maybe it should only be implemented in the case where find receives len(*args) == 1 but might also be useful if containing multiple args, then returning the dictionary with find_keys and flat lists of the desired element in the tuple for each list.
