### ISSUE TITLE
Exa editor should throw a warning if string passed looks like a file path but is not file

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#136]
Occasionally I will bork a file path when calling exa.Editor('/path/to/my/file') but the constructor happily assumes you want an Editor object with a single line whose contents are the broken file path. If it is a string and "looks" like a file path but os.path.isfile is False, maybe we should print a warning that you probably actually wanted a file that didn't get found. It would explain all sorts of IndexError/AttributeError/etc. down the line for subclasses when specific parse_methods are called but cannot execute properly. 

Or should we consider error catching using a different paradigm?

**Comment by avmarchenko** [comment]
I have had this error as well, I propose we check if a string that looks like a file by the following inside `editor.py`:
```
def check_path(path, ignore_warning=False):
    """
    Check if path is or looks like a file path (path can be any string data).

    Args:
        path (str): Potential file path
        ignore_warning (bool): Force returning true

    Returns:
        result (bool): True if file path or warning ignored, false otherwise
    """
    if (ignore_warning or os.path.exists(path) or
        (len(path.split("\n")) == 1 and (r"\\" in path or r"/" in path))):
        return True
    return False
```
The `ignore_warning` can be used when a non-existent path is required.

**Comment by avmarchenko** [comment]
And the implementation would be in the first line of the Editor's __init__:

```
def __init__(...):
    if check_path(data):
    ...
```

**Comment by avmarchenko** [comment]
This has been backported from internal 0.4.0 alpha code into the 0.3.9 milestone
