### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exa#161]
The repository size is fairly large now and takes uncomfortably long to clone, for example. In this post: https://stackoverflow.com/questions/2116778/reduce-git-repository-size there are some hints on things that could be done to reduce the repo size. We should explore what can be done here.

**Comment by tjduigna** [comment]
I wonder if this is a remnant of the git history before the re-organization of js extensions into exatomic or crufty static data that is no longer a part of exa. Either way I agree that this should be addressed. As it stands today, exa should be pretty lean as a stand-alone package without its dependencies.

**Comment by avmarchenko** [comment]
Repo size is around 20MiB, descoping.
