### ISSUE TITLE
Epic 1: Editor re-write

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#166]
The `Editor` should be redesigned to be more efficient, and a `StructuredTextEditor` (e.g. csv) can serve as an example implementation.

**Comment by avmarchenko** [comment]
See also #151, #129

**Comment by avmarchenko** [comment]
Line 381 in the current `editor.py` => the maximum file path length (in characters) on windows is an easy early exit that will prevent other types of errors downstream.

**Comment by tjduigna** [comment]
I think if there's any hope to maintaining compatibility with exatomic in exa 1.0 we will already have enough work converting to the updated data structures that significantly changing the `Editor` API would likely break all the bespoke parsing logic for the various codes. I think there is still a valuable add in a `StructuredTextEditor` and will close this in favor of that.
