### ISSUE TITLE
Epic 2: Implement Data class

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#167]
A new `Data` class will act as an abstraction layer between a data provider (e.g. `Editor` or `DAO`) and the data itself. This `Data` class is intended to manage different data providers in a consistent manner. This additional class layer will likely eliminate the need to subclass the `pd.DataFrame` entirely (by adopting a "composability" paradigm).

```python
import exa
i = exa.Isotopes()
c = exa.Constants()
i.data().shape # (3181, 15)
c.data().shape # (335, 4)
```

The initial implementation has the following properties:
- Assumes a data provider is a callable that takes no arguments in the constructor (limitation)
- Internally stores the current data in `self._data`, which is accessible by the `data()` method
- Has traits for passing args and kwargs to the data provider when it is called
- Has preliminary validation when `self._data` is a `pd.DataFrame`, otherwise it is not validated
- Begins to implement the expectations of `exa`, where `index` name will be set, `columns` presence are enforced, and `categories` are converted to categoricals.
- Can be instantiated from a YAML configuration, e.g. `exa/static/isotopes.yml`.

I can think of many additional validations and conveniences that would be useful to optionally support in the `Data` class, including:
- a `unique` tuple of column names which will enforce a uniqueness constraint
- an `aliases` or `internal_repr` dictionary mapping columns provided by the data provider to `Data`.
- a `dtypes` dictionary (like `categories`, perhaps this supersedes it) to enforce type conversion
- perhaps a way to optionally specify some info about the type conversion? (looking at you datetimes)

**Comment by tjduigna** [comment]
Based on a question raised in #177 (copied here):
In the tests I see source_args and kwargs. Were those intended to be passed to the constructor of 
the class? Is functools.partial something we could use here to ship args for callables (taking a bit of 
functional programming possibly)?

My first thought was to expect `Data` to `__call__` a data provide. Then the data provider could be called flexibly through the `Data` by updates to `source_args` and kwargs. But it is definitely possible that the data provider could be a complicated object requiring instantiation. I briefly thought about something like `[source_]init_args` and kwargs but that starts to feel cumbersome.

I am trying to keep in mind the ability to define `Data` from a config file. This has implications for the level of sophistication of the references in the config though. It may get hairy with lots of dynamic importing. However, a data provider could be similarly and/or independently generated from a configuration and provided to the `__init__` directly.

**Comment by avmarchenko** [comment]
Can you show an example of defining data from a config file? Maybe config definitions can only "use" `Data` kinda how `Isotopes` and `Constants` are created? It may be a limitation but for a first implementation I think its ok.

**Comment by tjduigna** [comment]
The API as described has largely been implemented. The remaining details will be fleshed out as subclasses are implemented and Container integration continues. Closing this in favor of targeting those issues directly.
