### ISSUE TITLE
Epic 5: Remove meta-classes

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#170]
By going all in on `traitlets`, we can get almost all the functionality that the meta-class system provides, without the maintenance fees. Additionally, we can leverage the event driven system wherever convenient and could see synergistic benefits in consistency and simplicity all the way down to `exatomic`'s widget configuration.

**Comment by avmarchenko** [comment]
My understanding is this should deprecate (remove from the code-base) everything related to `typed.py` right?

**Comment by tjduigna** [comment]
In principle we should mostly be able to rely on the mechanisms provided by `traitlets`, so this would indeed deprecate `typed.py`.
