### ISSUE TITLE
Discussion for 1.0:

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#173]
Do we drop support for Python 2? Consensus so far is yes.
If so, do we drop <3.6 support? Jury is out on 3.5 support for now.

Should we adopt a code formatter such as Black?
If so, do we enforce a pre-commit hook?

Please update with any relevant design questions for a 1.0 release.

**Comment by avmarchenko** [comment]
I'm a big fan of black for automatic formatting. Also in use (in my workflow) is flake8. We could enforce black as a precommit hook and run flake8 during CI? I support dropping python < 3.6.

**Comment by tjduigna** [comment]
Some of this is starting to be addressed. Other topics are more conversational and belong in the slack chat. Took notes on black and flake8 and will update the issue board in due time. Closing this to reduce noise.
