### ISSUE TITLE
Clean up field generation on JS side

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#72]
Currently the Field class (on the python side) has the following columns:

nx, ny, nz, ox, oy, oz, xi, xj, xk, yi, yj, yk, zi, zj, zk

but the Field class (on the JS side) uses the following attributes (and assumes a cubic cube file):

nx, ny, nz, xmin, ymin, zmin, dx, dy, dz, (xmax, ymax, zmax, x[:], y[:], z[:], xvalues, yvalues, zvalues)

where the ones in parentheses need not be shipped back to python. If we have xmin, dx and nx we have x[:]/xvalues defined for us. The attributes on the JS side can be streamlined to reflect more closely the attributes on the python side, regardless of the internal implementation of x/y/zvalues on the JS side.

**Comment by alexvmarch** [comment]
As discussed yesterday, the plan is to make all pieces of codes systematic and consistent with the python field; this gives the most flexibility for non-cubic discrete fields. This won't have an impact on the API; it is all internal refactoring. Also, this is a reminder for me to do this, today.

**Comment by tjduigna** [comment]
While we should be consistent between python and JS i think we should only store the data directly in the cube file. Eg; don't do the computation for xmax, just store ox and dxi, dxj, dxk, etc.

**Comment by alexvmarch** [comment]
The infrastructure for passing the actual arrays x, y, z to class field exists so as suggest we now accept field creation using this approach. Ref: 536da60e73816c7c33db31b245238fd13338ead6.
See also 6f05a00195ed3d92322992f1cc723cc6d8d7ebda in atomic.
