### ISSUE TITLE
Widget or Container should provided a pythonic api for GUI controls

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exa#83]
This will simplify passing default options from the python side to the javascript side. Note that this API should be compatible with a standalone webapp so it may be advantageous for the Container to have this API - in principle the GUI for a type of data container is systematic regardless of whether it is being view in the notebook or in the standalone webapp

**Comment by tjduigna** [comment]
Sounds like a good design goal for the next release. I do think that it should be at the most root level possible to stay flexible and extensible.

**Comment by avmarchenko** [comment]
No longer applicable because widgets have been removed.
