### ISSUE TITLE
app3d cylinder performance

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exa#84]
Suspicion is that newly implemented cylinders are causing a dramatic FPS drop on animation. Need to figure out what is causing the slowdown for sure and come up with a fix. Could consider line shader to make the line look cylinderical rather than using CylinderGeometry.

**Comment by tjduigna** [comment]
It looks like rendering the pipes before spheres doesn't entirely solve the z fighting issue. If only linewidth was supported on windows... But I agree maybe cylinders aren't the best way to go.

**Comment by alexvmarch** [comment]
Tested current implementation on a few machines with dedicated graphics cards and performance was markedly improved (e.g. on some ancient hardware - nvidia 9800GT - performance was good up to ~60 fps).

**Comment by avmarchenko** [comment]
No longer applicable.
