### ISSUE TITLE
Adding the reverse conceptual direction of the editor class

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exa#97]
The Editor class is intended to interact with files on disk, parse them, and create the container (exatomic's universe) object. Upon successful creation of the container, it would be nice to be able to generate new text files in various file formats as determined by Editor's subclasses.

One approach to this idea:

```python
class Editor:
    @classmethod
    def from_container(cls, container):
        parsed = cls.class_specific_string_builder(container)
        return cls(parsed)

    def class_specific_string_builder(self, container):
        raise NotImplementedError()

class SubEditor(Editor):
    def class_specific_string_builder(container):
        return correct_string
```

**Comment by avmarchenko** [comment]
Closed by #101
